header:
  productionDescription: > 
     <p> This is a sample server Petstore server.</p>
featuredFeatures:
  - title: Pets
    description: >
      Quickly add, update, find, or delete your pets. You can manage all of your pets using this feature as well as upload pictures.
    tags: ["pets", "api"]
    bullets: ["Increase payment security and reduce risk", "No need to store personal customer information", "Less operational costs", "Improved customer experience"]
    links: ["docs/Resources/API-Documents/Payments_VAS/Payment-Token.md"]
  - title: Store
    description: >
      Place, find, or delete orders at your store. You can manage inventory and keep track of your store.
    tags: ["store", "api"]
    bullets: ["Faster acceptance than credit or debit", "Biometric security", "Global offering and acceptance"]
    links: ["docs/Online-Mobile-Digital/Wallets-AltPayments/Apple-Pay/Apple-Pay.md"]
  - title: User
    description: >
      You are also able to create, get, update, or delete your users. You are also able to log-in and log-out a user.
    tags: ["user", "api"]
    bullets: ["Modern technology stack", "Automated backoffice", "Fast testing, certification and implementation"]
    links: ["docs/Resources/API-Documents/Use-Our-APIs.md"]
benefits:
  - title: Organziation
    description: >
      You can manage your pets, users, and orders in a concise simple manner.
  - title: Increase Sales
    description: >
     A simplified platform allows for customers to place orders with ease.
  - title: Innovation
    description: >
      Online petstores are cool.
featuredAPIs:
  - name: Add Pet
    description: Used to add a pet.
    type: post
    path: /pet
    codeSample: '[json
                  {
                    "id": 0,
                    "category": {
                      "id": 0,
                      "name": "string"
                    },
                    "name": "doggie",
                    "photoUrls": [
                      "string"
                    ],
                    "tags": [
                      {
                        "id": 0,
                        "name": "string"
                      }
                    ],
                    "status": "available"
                  }
                ]'
    language: Curl
    link: link to API Explorer
  - name: Update Pet
    description: Updates a pet
    type: put
    path: /pet
    codeSample: '[json
                   {
                    "id": 0,
                    "category": {
                      "id": 0,
                      "name": "string"
                    },
                    "name": "doggie",
                    "photoUrls": [
                      "string"
                    ],
                    "tags": [
                      {
                        "id": 0,
                        "name": "string"
                      }
                    ],
                    "status": "available"
                    }
                  ]'
    language: Curl
    link: link to API Explorer 
  - name: Place Order
    description: Places order for a pet
    type: post
    path: /store/order
    codeSample: '[json
                  {
                    "id": 0,
                    "petId": 0,
                    "quantity": 0,
                    "shipDate": "2021-06-21T21:55:37.319Z",
                    "status": "placed",
                    "complete": true
                   }
                  ]'
    language: Curl
    link: link to API Explorer  
  - name: Find Order
    description: Find purchase order by ID
    type: get
    path: /store/order/{orderID}
    codeSample: '[json
                  {
                    "id": 0,
                    "petId": 0,
                    "quantity": 0,
                    "shipDate": "2021-06-21T21:57:19.714Z",
                    "status": "placed",
                    "complete": true
                  }
                  ]'
    language: Curl
    link: link to API Explorer
  - name: Create user
    description: Creates a new user
    type: post
    path: /user
    codeSample: '[json
                  {
                    "id": 0,
                    "username": "string",
                    "firstName": "string",
                    "lastName": "string",
                    "email": "string",
                    "password": "string",
                    "phone": "string",
                    "userStatus": 0
                   }
                  ]'
    language: Curl
    link: link to API Explorer
useCases:
  - title: Find the Perfect Pet
    subtitle: Pets
    description: > 
      Customers can find their new best friend by checking which pets are available and browsing through pet images. 
      Shopkeepers can easily update an existing pet's data by finding that pet's petId and add and delete pets to reflect their inventory.
  - title: Effective and Effecient Inventory Management 
    subtitle: Store
    description: > 
      Shopkeepers are treated with an innovative petkeeping system that tracks orders with their respective orderIDs and can retrive shopkeepers' pet inventory by status with ease.
  - title: User Account Management
    subtitle: User
    description: > 
      Customers can customize their own shopping expereince by creating accounts that they can easily login and logout of.
      Shopkeepers can keep track of their customers with this system.  
